version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/conf/nginx:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    links:
      - php
    networks:
      - internal
  php:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/var/www/html
      - ./docker/conf/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      db:
        condition: service_healthy
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: food
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 20
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.1/28